// <auto-generated />
using System;
using Biodigestor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biodigestor.Migrations.Temperatura
{
    [DbContext(typeof(TemperaturaContext))]
    partial class TemperaturaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biodigestor.Models.BiodigestorClass", b =>
                {
                    b.Property<int>("IdBiodiestor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdBiodigestor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBiodiestor"));

                    b.Property<string>("ModeloBiodigestor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreBiodigestor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VolumenGas")
                        .HasColumnType("int");

                    b.HasKey("IdBiodiestor");

                    b.ToTable("Biodigestores", (string)null);
                });

            modelBuilder.Entity("Biodigestor.Models.Temperatura", b =>
                {
                    b.Property<int>("IdTemperatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTemperatura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTemperatura"));

                    b.Property<int>("IdBiodigestor")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaTemperatura")
                        .HasColumnType("datetime2");

                    b.Property<float>("nivelTemperatura")
                        .HasColumnType("real");

                    b.HasKey("IdTemperatura");

                    b.HasIndex("IdBiodigestor");

                    b.HasIndex("IdTemperatura")
                        .IsUnique();

                    b.ToTable("Temperatura", (string)null);
                });

            modelBuilder.Entity("Biodigestor.Models.Temperatura", b =>
                {
                    b.HasOne("Biodigestor.Models.BiodigestorClass", "Biodigestor")
                        .WithMany()
                        .HasForeignKey("IdBiodigestor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biodigestor");
                });
#pragma warning restore 612, 618
        }
    }
}
